### PR TITLE
Added guide for mask region.

### PR DESCRIPTION
**Pull request by Symbiomatrix**

### CODE REVIEW

**Comment by hako-mikan** [comment]
Thanks.
I'm trying to merge your inpaintmask and region by prompt.
At same time, I'm splitting up the long code now.

In my environment, errors `No module named 'PBRemTools'` was appear,
Could you write a commentary on the installation of PBRemTools?

**Comment by Symbiomatrix** [comment]
o.o
Never heard of it, don't have it. Mask runs on torchvision, cv2 and colorsys. You sure it didn't slip in from elsewhere? It kinda looks like your batch clipper. Where's the error popping up?

**Comment by hako-mikan** [comment]
Thanks advice.
I found cause. When merging script, I used auto fix of VScode.
It was due to some mistake or misconversion at that time, and code was added to the cv2 import that called PBRemTools. Sorry.

**Comment by hako-mikan** [comment]
it works well, Great!
canvas

**Comment by hako-mikan** [comment]
New version is uploaded
I would like to test it some more and if there are no problems, I would like to publish it.
https://github.com/hako-mikan/sd-webui-regional-prompter/tree/ver7

**Pull request merged**
