### PR TITLE
Two dimensional - fix.

### PR DESCRIPTION
**Pull request by Symbiomatrix**
I brainstormed with a mathematician buddy, and it seems that extracting the dimensions isn't so straightforward after the fact because of the repeated rounding.
However, if we can assume that the reduction / expansion operation applied between layers is always a variant of ceil(x/2) for each of H and W (which I'm not sure applies to every checkpoint, but it holds in mine), then the specific power of 2 can be inferred via logarithm rounding, then applied to the height / width in the same manner.
Under this assumption, this fix should work correctly for every pair of input dimensions.
I've also incorporated the simple fix to img2img, #8 .

I'm not really sure what's up with the commit merge thing, it's completely out of whack for me even though it should be just a minor change.

### CODE REVIEW

**Comment by hako-mikan** [comment]
I am testing and it is working. Excellent.
Thanks to fixing #8

**Comment by hako-mikan** [comment]
updated README.
https://github.com/hako-mikan/sd-webui-regional-prompter/blob/ver3/README.md
Please check it and correct if there are any oddities. I am not a native.

**Comment by Symbiomatrix** [comment]
Thanks for the mention. Overall, nice work.
I think the one sentence explanation about the ratio was a bit short compared to what it might do behind the scenes, yet the picture clarifies it much better than it would have been to understand through a long description, so I would stick with that.
Plus it shouldn't matter if using COL/ROW and a precise distribution of regions.
It might be useful to add an example of ADDBASE to the picture, if you can manage it.

I can't stress how wonderfully intuitive the picture explanation / infographic is. A second infographic would go a long way, for example: a lengthwise scene, with a simple multi row broadcast from (1; 2; 3,1,2) to (1,1,.. ;2,2... ;3,1,2) would help clarify that function quickly. Though it might be sliding into tutorial territory, I don't have much experience with this.

**Comment by hako-mikan** [comment]
Thanks comment. 
Updated to enable long tokens and common prompts. 
It is working well. I will release the updated version after some more testing.

**Pull request merged**
