### PR TITLE
EXPERIMENTAL: Fixed ddim / plms crash.

### PR DESCRIPTION
**Pull request by Symbiomatrix**
Addresses #13.

Matched x.pos, x.neg with context.pos, context.neg, and in vanilla samplers their tensor position is reversed.

Also removed redundant return from lora_namer.

Hako - this was basically just a lucky guess, if you can confirm that the architecture actually fits this description, that'd be great. I also haven't thoroughly tested other samplers and features, so that's important too (although I believe I've limited the fix by sampler sufficiently). "I have no idea what I'm doing", as the meme goes.
I'm finding negatives are far less responsive, but that could just be ddim in general, I don't use it regularly.

### CODE REVIEW

**Comment by Sakura-Luna** [comment]
Can you try to repair UniPC? Originally, it will report the same error as DDIM. Now that DDIM supports it, UniPC will only output weird results.

**Comment by Symbiomatrix** [comment]
@Sakura-Luna Haven't heard of unipc. Is it a sampler? Was it added to webui in the last 2 months, or does one need to obtain it separately?

**Comment by Sakura-Luna** [comment]
@Symbiomatrix It's been a while since [UniPC](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7710) was added.

**Comment by Symbiomatrix** [comment]
It's been a while since I've upgraded. : )
Alright, I'll have a look once I'm up to speed. If you'd like, you could try adding it to the isvanilla list and see if it does anything. "Weird results" is definitely how I'd describe the initial tests with the wrong selection of weights.

**Comment by Sakura-Luna** [comment]
It seems to work, thanks.

**Pull request merged**
