### PR TITLE
Bugfix for lora names.

### PR DESCRIPTION
**Pull request by Symbiomatrix**
Addresses #126 .

### CODE REVIEW

**Comment by Faramour** [comment]
Tested latest commit with `scripts/latent.py` edited according to this PR, the bug still happens (the regioner print comes from #126)
```
regioner [{'botw_style_offsetadded_by_regional_prompter0.9609437077106666': 0.7}, {'botw_style_offsetadded_by_regional_prompter0.9609437077106666': 0.7}, {'botw_style_offsetadded_by_regional_prompter0.9609437077106666': 0}] [{'botw_style_offsetadded_by_regional_prompter0.9609437077106666': 0.7}, {'botw_style_offsetadded_by_regional_prompter0.9609437077106666': 0}, {'botw_style_offsetadded_by_regional_prompter0.9609437077106666': 0.7}]
Error running process_batch: E:\SD_A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "E:\SD_A1111\stable-diffusion-webui\modules\scripts.py", line 436, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "E:\SD_A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 363, in process_batch
    lora_namer(self, p, lnter, lnur)
  File "E:\SD_A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 227, in lora_namer
    regioner.ndeleter(lnter, lnur, lorder)
  File "E:\SD_A1111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 322, in ndeleter
    self.te_llist[0][flokey(key)] *= val
KeyError: 'botw_style_offset'
```

**Comment by Symbiomatrix** [comment]
@Faramour You're right, I had it backwards: should save the full key name which is unique to each region. Please check out the corrected version.
I guess the extra text is supposed to discriminate multiple loras in different regions and across generations. But I'm not sure it's working correctly, because shin_key matches and updates llist in every place it occurs, thus most likely amplifying the lora effect. @hako-mikan ?

**Comment by Faramour** [comment]
Tested with multiple loras, works fine now.
As to multiple uses of same lora amplifying it's effect, I did notice this being the case during testing. Two examples I stumbled into when doing the tests with 2 regions in Horizontal mode and common prompt enabled):
- Lora with weight 0.5 used in common prompt generates an image as if the lora with weight 1 was applied to the entite image,
- The same lora called in each region's subprompt (no lora in common prompt) with weight 0.5 generates an image as if the lora with weight 1 was applied to the entire image.

**Comment by Symbiomatrix** [comment]
Aye, that's exactly what it looks like. What I'm not certain about is the intent, since I don't know how the split affects the custom lora_forward, and I haven't used block weight. Shouldn't be too difficult to match regions, but I'd rather know what I'm doing.

**Pull request merged**
