### PR TITLE
Converted presets to json.

### LINKED ISSUE #61: Apply Presets Error
4a9b57834dc7ffa763febd202e447732f63cbe29

このコミットあたりからプリセットを適用しようとするとエラーが出るようになりました
解決するにはどうしたらいいのでしょうか？

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 422, in setpreset
    preset[3],preset[4],preset[5],preset[7],preset[8]= booler(preset[3]),booler(preset[4]),booler(preset[5]),booler(preset[7]),booler(preset[8])
IndexError: list index out of range

### PR DESCRIPTION
**Pull request by Symbiomatrix**
Fixes #61, and should allow adding parameters more easily in the future.
Not sure if there's a way to make certain values not cause an update (if null).
Tried to make it human readable, seems to be on my end.
I've changed a couple things:
- If load fails, it will *always* attempt to init rather than only if the file doesn't exist, should the file happen to be corrupted. There might be a better way, I can't think of anything (other than maybe make a backup copy).
- Will always prevent duplicate keys, updating them. Should also probably add a button to delete presets.

### CODE REVIEW

**Comment by hako-mikan** [comment]
I have other repositories and you are always helpful.

**Comment by Symbiomatrix** [comment]
Pardon, not quite sure I understood: Do you mean you need to attend the other repos, or would like some help.
If it's the latter, I've had a look and don't think I could be of much help there. I'm little more than a tinkerer with breakpoints and that's pretty heavy model stuff. Plus, kinda dropping the ball already with my other RL tasks, sorry.
In any case, thanks; I try to do what I can.

**Comment by hako-mikan** [comment]
I’m sorry for my poor English. I wanted to express my gratitude for your cooperation in this repository because I also manage other repositories and sometimes don’t have time.

**Comment by Symbiomatrix** [comment]
Ah, I see. Don't mention it, chum. Your time would be put to better use on more complex concerns than little boilerplate upgrades and poorly described user problems, I have quite a bit of experience with those. : )

**Pull request merged**
