### PR TITLE
Two dimensional - Rows / columns first, V2.

### PR DESCRIPTION
**Pull request by Symbiomatrix**
Hey, hako.
Quick & dirty patch to allow horizontal / vertical indication to control whether rows or columns are the outer and inner parts of the prompt.
For example, (p1 ROW p2 COL p3);
In horizontal mode, will be interpreted as first row with one column (p1), second row with 2 columns (p2,p3).
In vertical mode, will be interpreted as first column with two rows (p1,p2), second column with 1 column (p3) - which is impossible to pull off in horizontal mode.
This means that the aratios parameter is fully inverted as well: for example, the above prompt's values might look like (1;2;3,4); the columns will be (1,4) and rows will be (2,3) | (4 broadcast). I'm not entirely happy with the flip switching from horizonal to vertical, but it does the job.

Also, small fix to broadcast throwing errors when there are more rows than in anchor (due to bad while stop).

---

Merged recent changes to token count and common prompts.
Also fixed a few cosmetics, and changed the usecom / ncom so that they automatically flag true when ADDCOMM is prompted, same as with base.
I recommend switching to self.useX properties instead of parameters in all functions to keep the signatures short - I'm not entirely sure about some places, and left them out.
Tested on base + common, horizontal and vertical.

### CODE REVIEW

**Comment by hako-mikan** [comment]
Thanks alot, I test it.

The update to LoRA is largely complete and I hope to merge it at some point. 
This update works through a different mechanism than the existing Attention method, 
so I don't assume that merging them will cause any problems.

**Comment by hako-mikan** [comment]
It seems to work in case good value for a cut such as 640 * 640 for complex ratios used in README(1,2,1,1;2,4,6). but i met error in 600 * 400. I'll try to verify it a bit more.

**Comment by Symbiomatrix** [comment]
Copy that, reproduces on my end, on it.

**Comment by Symbiomatrix** [comment]
Got it, missed some dsh / dsw's. Fix coming up.

**Comment by Symbiomatrix** [comment]
Nope, had it backwards - when cutting out, dsh and dsw should be constant, so actually have to flip that in the second section.

**Comment by Symbiomatrix** [comment]
Done, #12 .

**Pull request merged**
